apiVersion: v1
kind: Pod
metadata:
  name: mysite
  labels:
    function: webserver
spec:
  containers:
  - name: httpd
    image: ghcr.io/aleale00/cis-92:milestone-6.0
    ports:
    - containerPort: 80
    livenessProbe:
        httpGet:
          path: /polls/
          port: 8080
    env:
      - name: SECRET_KEY
        value: "fdgdfgfdg"
      - name: DB_NAME
        value: "mysite"
      - name: DB_USER
        value: "postgres"
      - name: DB_PASSWORD
        value: "django"
      - name: DB_HOST
        value: "postgres"
